{% set name = "plac" %}
{% set version = "1.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7c16cfa7422a76b7525fc93d0be5c9c9a2d5250083e80ddac6621edb395dc081" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - plac

about:
  home: https://micheles.github.io/plac/
  # license_file: No license yet - see https://github.com/micheles/plac/issues/26
  license: BSD 2-Clause
  license_family: BSD
  summary: 'The smartest command line arguments parser in the world'
  doc_url: https://micheles.github.io/plac/
  dev_url: https://github.com/micheles/plac

extra:
  recipe-maintainers:
    - pmlandwehr
