{% set name = "plac" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c91a4c9f9cc67c7e7213b6823b0ea15cd0afe5eaf8f8dda1fe5cb10192b137f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - plac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://micheles.github.io/plac/
  license_file: LICENSE.txt
  license: BSD-2-Clause
  license_family: BSD
  summary: The smartest command line arguments parser in the world
  doc_url: https://micheles.github.io/plac/
  dev_url: https://github.com/micheles/plac

extra:
  recipe-maintainers:
    - jan-janssen
