{% set name = "plac" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/plac-{{ version }}.tar.gz
  sha256: 86a50abd40c5a6ea9695b45a1f08637e744e0a57249c24d1593cad9eda1f8aac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - plac
    - plac_core
    - plac_ext
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ialbert/plac
  summary: The smartest command line arguments parser in the world
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
