{% set name = "plac" %}
{% set version = "1.3.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2e6422d966ca2cbe30353ad13f1c44fddfa71f8445fb54fff0169d3c982101be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - plac

about:
  home: https://micheles.github.io/plac/
  license_file: LICENSE.txt
  license: BSD 2-Clause
  license_family: BSD
  summary: 'The smartest command line arguments parser in the world'
  doc_url: https://micheles.github.io/plac/
  dev_url: https://github.com/micheles/plac

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
