schema_version: 1

context:
  name: plac
  version: "1.4.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/plac-${{ version }}.tar.gz
  sha256: 957ffbab8ea8ab8c0b9f2694daa2a95f3560151cd162bcbc91e97ff94d45c4f9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - plac
        - plac_core
        - plac_ext
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: The smartest command line arguments parser in the world
  license: BSD-2-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/ialbert/plac

extra:
  recipe-maintainers:
    - jan-janssen
