travis:
  secure:
    BINSTAR_TOKEN: eL7DneYisyJ315XC50SAqsMgx4ejBL8peZbmvvY/b7101MXNu1m16E8G7ysbYjsg8KQLjKysGXrW9hoR0Q2x9qDxTCtYap2ZEjiNNlas7YCTNW7AlVDsg1FkDPGT4uBWMhdrDSSnn+THSmdcLAjbssvy5geoLbGF6EXIzXSSmUGIsXkRTxRFQwstlY9MRDYtTK4khUzHFZSI4URmvC4werj7VtrYm+912FGOzob/Es7kMdevadibkoV7EbeVIawdXGuQxOFpGb/0cuQ8PjvtE0bVpDKlU3tu9LkEIvrHaytoGQz6MSxCVjFLaWPclZqZljnT1nMOW80bwFDMvSN/qQAkJLf+UzB0TjGsGzassVICOV9aT2EbdYZgkJ2vLUyVKafWzhlHP3EoWPzV1iwTnQsv/NgIbTxXFwFUpc/MCzU2M4qV9S2DZqpw02FmmT4ikF8AZr3aC6lNu2GC+Z7tis4xdjnTFgaxo3srFuIqHW00iwuLbuoTgTJcmW1n/CscQWyISxaKA8tpV7Vjz77hs7L/GlMdosuSuevgu8T0pic8Nqp3TcK54q3A1+sFbx3Qf47ppYIfyaC7wpooXl6ab0JSb72kOjgsXHfeqnGI9ZUZwS8MMKC2hE8f6S5dw6u4AcJS3f/oKaT7ckhjVADIm4pvcLmGh3Wzt4Rh6EqjlEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
